<a href="https://colab.research.google.com/github/octaviadyah3/sentimenanalysis-using-lexiconbased-and-logisticregression/blob/main/ML_KLASIFIKASI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/octaviadyah3/sentimenanalysis-using-lexiconbased-and-logisticregression.git

Cloning into 'sentimenanalysis-using-lexiconbased-and-logisticregression'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 26 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (26/26), 1.66 MiB | 11.25 MiB/s, done.
Resolving deltas: 100% (6/6), done.


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df_train = pd.read_excel("/content/sentimenanalysis-using-lexiconbased-and-logisticregression/hasil_sentimen_polarity.xlsx")
df_train
df_train.head()

Text Filtering  Polarity Score  \
0  ['sidang', 'perdana', 'sengketa', 'hasil', 'pi...              -2   
1  ['felixbolanosg', 'vuestra', 'memoria', 'felis...               0   
2  ['isi', 'gugat', 'sengketa', 'pilpres', 'ganja...               0   
3  ['putrynusantara', 'ayamsegar', 'tim', 'hore',...             -10   
4  ['blueberets', 'wkwkwk', 'bujer', 'coba', 'ali...               1   

  Indonesia Sentiment  
0            Negative  
1             Neutral  
2             Neutral  
3            Negative  
4            Positive

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

In [5]:
X_train, X_val, y_train, y_val = train_test_split(
    df_train[["Text Filtering", "Polarity Score"]],
    df_train["Indonesia Sentiment"],
    test_size=0.2,
    shuffle=True
)

# Menggunakan TfidfVectorizer untuk memproses teks
vectorizer = TfidfVectorizer()
X_train_text_tfidf = vectorizer.fit_transform(X_train["Text Filtering"])
X_val_text_tfidf = vectorizer.transform(X_val["Text Filtering"])

# Menggabungkan hasil TF-IDF dengan fitur Polarity Score
X_train_combined = hstack([X_train_text_tfidf, X_train["Polarity Score"].values.reshape(-1, 1)])
X_val_combined = hstack([X_val_text_tfidf, X_val["Polarity Score"].values.reshape(-1, 1)])

In [6]:
# Initialize the Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb_tfidf = MultinomialNB()

# Assuming 'X_train_text_tfidf' from previous cells holds the vectorized data
nb_tfidf.fit(X_train_text_tfidf, y_train)  #model

# Similarly, for predictions, use 'X_val_text_tfidf'
y_pred = nb_tfidf.predict(X_val_text_tfidf)

# Menghitung dan mencetak laporan klasifikasi
print("Classification Report:")
print(classification_report(y_val, y_pred))

# Menghitung dan mencetak matriks kebingungan (confusion matrix)
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# Menghitung dan mencetak F1 Score
f1 = f1_score(y_val, y_pred, average='weighted')
print(f"F1 Score (weighted): {f1}")

# Menghitung dan mencetak Accuracy Score
accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy Score: {accuracy}")

Classification Report:
              precision    recall  f1-score   support

    Negative       0.64      0.97      0.77       172
     Neutral       0.70      0.43      0.53        72
    Positive       1.00      0.05      0.09        61

    accuracy                           0.66       305
   macro avg       0.78      0.48      0.47       305
weighted avg       0.73      0.66      0.58       305

Confusion Matrix:
[[166   6   0]
 [ 41  31   0]
 [ 51   7   3]]
F1 Score (weighted): 0.5803328151498021
Accuracy Score: 0.6557377049180327


In [7]:
rf_tfidf = RandomForestClassifier()

# Assuming 'X_train_text_tfidf' from previous cells holds the vectorized data
rf_tfidf.fit(X_train_text_tfidf, y_train)  #model

# Similarly, for predictions, use 'X_val_text_tfidf'
y_pred = rf_tfidf.predict(X_val_text_tfidf)

# Menghitung dan mencetak laporan klasifikasi
print("Classification Report:")
print(classification_report(y_val, y_pred))

# Menghitung dan mencetak matriks kebingungan (confusion matrix)
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# Menghitung dan mencetak F1 Score
f1 = f1_score(y_val, y_pred, average='weighted')
print(f"F1 Score (weighted): {f1}")

# Menghitung dan mencetak Accuracy Score
accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy Score: {accuracy}")



Classification Report:
              precision    recall  f1-score   support

    Negative       0.77      0.86      0.81       172
     Neutral       0.64      0.85      0.73        72
    Positive       0.65      0.18      0.28        61

    accuracy                           0.72       305
   macro avg       0.69      0.63      0.61       305
weighted avg       0.71      0.72      0.69       305

Confusion Matrix:
[[148  19   5]
 [ 10  61   1]
 [ 35  15  11]]
F1 Score (weighted): 0.6861929905153675
Accuracy Score: 0.7213114754098361


In [8]:
lr_tfidf = LogisticRegression(solver='liblinear', C=10, penalty='l2', multi_class='ovr')
# Assuming 'X_train_text_tfidf' from previous cells holds the vectorized data
lr_tfidf.fit(X_train_text_tfidf, y_train)  #model

# Similarly, for predictions, use 'X_val_text_tfidf'
y_pred = lr_tfidf.predict(X_val_text_tfidf)

# Menghitung dan mencetak laporan klasifikasi
print("Classification Report:")
print(classification_report(y_val, y_pred))

# Menghitung dan mencetak matriks kebingungan (confusion matrix)
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# Menghitung dan mencetak F1 Score
f1 = f1_score(y_val, y_pred, average='weighted')
print(f"F1 Score (weighted): {f1}")

# Menghitung dan mencetak Accuracy Score
accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy Score: {accuracy}")

Classification Report:
              precision    recall  f1-score   support

    Negative       0.77      0.89      0.82       172
     Neutral       0.68      0.74      0.71        72
    Positive       0.68      0.31      0.43        61

    accuracy                           0.74       305
   macro avg       0.71      0.65      0.65       305
weighted avg       0.73      0.74      0.72       305

Confusion Matrix:
[[153  10   9]
 [ 19  53   0]
 [ 27  15  19]]
F1 Score (weighted): 0.7173448292811044
Accuracy Score: 0.7377049180327869
